/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:549d6b5d-5cc5-4da7-8fd1-c99b24d50ed5",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_8cgjp4DVi",
    "aws_user_pools_web_client_id": "6gjfrqd2rf476k8ngcojqna7jl",
    "oauth": {}
};


export default awsmobile;
