/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:15197dfc-bd72-4bc8-b514-eaedf8344edf",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_F0eKi6wDk",
    "aws_user_pools_web_client_id": "1aqh4v6skp6a63v7t1fsmnm9me",
    "oauth": {}
};


export default awsmobile;
